### PUBLIC
### sitemap.xml
GET http://localhost:3000/sitemap.xml

### robots.txt
GET http://localhost:3000/robots.txt

### favicon
GET http://localhost:3000/favicon.ico



### UI
### Index
GET http://localhost:3000/

### Stock
GET http://localhost:3000/it/aasen-sparebank

### Stock news
GET http://localhost:3000/it/aasen-sparebank/news

### Stock dividend
GET http://localhost:3000/it/aasen-sparebank/dividend

### Stock target-price
GET http://localhost:3000/it/aasen-sparebank/target-price

### Exchanhe Milano
GET http://localhost:3000/it/milan


### Wrong url
GET http://localhost:3000/wrong-url



### API
### Wrong isin
GET http://localhost:3000/api/stocks/123456

### OK A.B.P. NOCIVELLI
GET http://localhost:3000/api/stocks/IT0005439861

### OK Aeffe
GET http://localhost:3000/api/stocks/aeffe

### OK All stocks
GET http://localhost:3000/api/stocks/

### OK All stocks Milan Market
GET http://localhost:3000/api/stocks/milan

### OK All stocks accents
GET http://localhost:3000/api/stocks/accents

### OK All stocks accents by market
GET http://localhost:3000/api/stocks/accents/paris

### User not found
# POST http://localhost:3000/api/users
# content-type: application/json

# {
#     "email": "ciccio@email.it",
#     "nome": "Ciccio Pasticcio"
# }
### Welcome message
# POST http://localhost:8080/api/custom/follow
# Content-Type: application/x-www-form-urlencoded

# name=PippoBaudo&email=pippo@test.it&privacy=true&title=A2a
